# Generated by Django 4.2.19 on 2025-02-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VISIT',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=20)),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
